-- Make overselling impossible at the database level.
--
-- The application already prevents it twice: the catalogue only offers what
-- is in stock, and the order transaction decrements conditionally with
-- `WHERE "stockQuantity" >= :quantity`, so a concurrent order that would take
-- the count below zero updates no rows and the transaction aborts.
--
-- That conditional update is the real mechanism and it is correct. This
-- constraint is the backstop: it guarantees that no code path anywhere, now
-- or later, including a hand-written SQL fix at two in the morning, can leave
-- a variant holding a negative quantity. A negative stock count means a
-- physical device was sold twice, which is a refund, an apology and a lost
-- customer.
--
-- Written by hand because Prisma cannot express CHECK constraints. It will
-- not be regenerated by `prisma migrate dev`, so do not delete it.

ALTER TABLE "Variant"
  ADD CONSTRAINT "variant_stock_not_negative"
  CHECK ("stockQuantity" >= 0);

COMMENT ON CONSTRAINT "variant_stock_not_negative" ON "Variant" IS
  'A negative quantity means a device was sold twice. The order transaction decrements conditionally; this guarantees it.';

-- Money is never negative either. These are cheap to check and they catch a
-- whole class of arithmetic mistake at the point it would be written rather
-- than when somebody notices a strange invoice.
ALTER TABLE "Variant"
  ADD CONSTRAINT "variant_price_not_negative"
  CHECK ("priceCents" >= 0);

ALTER TABLE "OrderItem"
  ADD CONSTRAINT "order_item_quantity_positive"
  CHECK ("quantity" > 0);

ALTER TABLE "Order"
  ADD CONSTRAINT "order_totals_not_negative"
  CHECK (
    "subtotalCents" >= 0
    AND "shippingCents" >= 0
    AND "tradeInCents" >= 0
    AND "totalCents" >= 0
  );

-- A stock movement of zero records nothing and is always a bug in the caller.
ALTER TABLE "StockMovement"
  ADD CONSTRAINT "stock_movement_delta_not_zero"
  CHECK ("delta" <> 0);
