-- Make double booking impossible at the database level.
--
-- The application already prevents it twice: the availability engine never
-- offers a conflicting slot, and the booking transaction re-checks for an
-- overlap immediately before inserting. Both of those are necessary for a
-- good experience, but neither is a guarantee once more than one server
-- process can write at the same time, which is exactly what happens on a
-- serverless platform. Two requests can pass their overlap probe
-- concurrently and both insert.
--
-- This constraint closes that window. The database itself rejects the second
-- row, so a double booking becomes impossible rather than unlikely.
--
-- Written by hand because Prisma cannot express exclusion constraints. It
-- will not be regenerated by `prisma migrate dev`, so do not delete it.

-- GiST indexes cannot compare text or uuid with = without this extension,
-- and the constraint needs that for the dentist column.
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE "Appointment"
  ADD CONSTRAINT "appointment_no_overlap"
  EXCLUDE USING gist (
    "dentistId" WITH =,
    tstzrange("startTime", "endTime", '[)') WITH &&
  )
  -- Two details that are load bearing:
  --
  -- The '[)' bound makes the range half open, so a 10:00 to 10:45
  -- appointment does not collide with a 10:45 start. That matches the
  -- overlaps() predicate in lib/availability/overlap.ts exactly. With '[]'
  -- every back to back pair of appointments would be rejected.
  --
  -- The WHERE clause is not optional. Without it, a cancelled appointment
  -- would keep reserving its own slot forever and nobody could rebook the
  -- time it released.
  WHERE (status <> 'cancelled');

COMMENT ON CONSTRAINT "appointment_no_overlap" ON "Appointment" IS
  'Prevents two active appointments overlapping for the same dentist. Half open ranges, so back to back appointments are allowed. Excludes cancelled appointments so a cancellation genuinely frees its slot.';
